using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Mirror;
using System.Linq;

public enum FlagNation
{
    Afghanistan = 1,
    Alan = 2,
    Albania = 3,
    Algeria = 4,
    American_Samoa = 5,
    Andorra = 6,
    Angola = 7,
    Anguilla = 8,
    Antartica = 9,
    Antigua_and_Barbuda = 10,
    Argentina = 11,
    Armenia = 12,
    Aruba = 13,
    Australia = 14,
    Austria = 15,
    Azerbajan = 16,
    Bahrain = 17,
    Bangladesh = 18,
    Barbados = 19,
    Belarus = 20,
    Belgium = 21,
    Belize = 22,
    Benin = 23,
    Bermuda = 24,
    Bhutan = 25,
    Bolivia = 26,
    Bosnia_and_Herzegovina = 27,
    Botswana = 28,
    Brazil = 29,
    British_Virgin_Islands = 30,
    Brunel = 31,
    Bulgaria = 32,
    Burkina_Faso = 33,
    Burundi = 34,
    Cambodia = 35,
    Cameroon = 36,
    Canada = 37,
    Cape_Verde = 38,
    Cayman_Islands = 39,
    Central_African_Republic = 40,
    Chad = 41,
    Chile = 42,
    China = 43,
    Colombia = 44,
    Comoros = 45,
    Cook_Islands = 46,
    Costa_Rica = 47,
    Croatia = 48,
    Cuba = 49,
    Curaçao = 50,
    Cyprus_No_Mans_Area = 51,
    Cyprus = 52,
    Czech_Republic = 53,
    Democratic_Republic_Of_Congo = 54,
    Denmark = 55,
    Dijbouti = 56,
    Dominica = 57,
    Dominican_Republic = 58,
    East_Timor = 59,
    Ecuador = 60,
    Egypt = 61,
    El_Salvador = 62,
    Equatorial_Guinea = 63,
    Eritrea = 64,
    Estonia = 65,
    Ethiopia = 66,
    Falkand_Islands = 67,
    Faroe_Islands = 68,
    Federated_States_Of_Micronesia = 69,
    Fiji = 70,
    Finland = 71,
    France = 72,
    French_Polynesia = 73,
    French_Southern_and_Antartic_Lands = 74,
    Gabon = 75,
    Gambia = 76,
    Georgia = 77,
    Germany = 78,
    Ghana = 79,
    Greece = 80,
    Greenland = 81,
    Grenada = 82,
    Guam = 83,
    Guatemala = 84,
    Guernsey = 85,
    Guinea_Bissau = 86,
    Guinea = 87,
    Guyana = 88,
    Haiti = 89,
    Heard_Island_and_McDonald_Islands = 90,
    Honduras = 91,
    Hong_Kong_SAR = 92,
    Hungary = 93,
    Iceland = 94,
    India = 95,
    Indian_Ocean_Territories = 96,
    Indonesia = 97,
    Iran = 98,
    Iraq = 99,
    Ireland = 100,
    Isle_Of_Man = 101,
    Israel = 102,
    Italy = 103,
    Ivory_Coast = 104,
    Jamaica = 105,
    Japan = 106,
    Jersey = 107,
    Jordan = 108,
    Kazakistan = 109,
    Kenya = 110,
    Kiribati = 111,
    Kosovo = 112,
    Kuwait = 113,
    Kyrgyzstan = 114,
    Laos = 115,
    Latvia = 116,
    Lebanion = 117,
    Lesotho = 118,
    Liberia = 119,
    Libya = 120,
    Liechtenstein = 121,
    Lithuania = 122,
    Luxembourg = 123,
    Macao_SAR = 124,
    Macedonia = 125,
    Madagascar = 126,
    Malawl = 127,
    Malaysia = 128,
    Mali = 129,
    Malta = 130,
    Marshall_Islands = 131,
    Mauritania = 132,
    Mauritius = 133,
    Mexico = 134,
    Moldova = 135,
    Monaco = 136,
    Mongolia = 137,
    Montenegro = 138,
    Montserrat = 139,
    Morocco = 140,
    Mozambique = 141,
    Myanmar = 142,
    Namibia = 143,
    Nepal = 144,
    Netherlands = 145,
    New_Caledonia = 146,
    New_Zealand = 147,
    Nicaragua = 148,
    Niger = 149,
    Nigeria = 150,
    Niue = 151,
    Norfolk_Island = 152,
    North_Korea = 153,
    Northen_Cyprus = 154,
    Northern_Mariana_Islands = 155,
    Norway = 156,
    Oman = 157,
    Pakistan = 158,
    Palau = 159,
    Palestine = 160,
    Panama = 161,
    Papua_New_Guinea = 162,
    Paraguay = 163,
    Peru = 164,
    Philipinnes = 165,
    Pitcairn_Islands = 166,
    Poland = 167,
    Portugal = 168,
    Puerto_Rico = 169,
    Qatar = 170,
    Republic_Of_Congo = 171,
    Republic_Of_Serbia = 172,
    Romania = 173,
    Russia = 174,
    Rwanda = 175,
    Saint_Barthelemy = 176,
    Saint_Helena = 177,
    Saint_Kitts_and_Nevis = 178,
    Saint_Lucia = 179,
    Saint_Martin = 180,
    Saint_Pierre_and_Miquelon = 181,
    Saint_Vincent_and_the_Grenadines = 182,
    Samoa = 183,
    San_Marino = 184,
    Sao_Tome_and_Principe = 185,
    Saudi_Arabia = 186,
    Senegal = 187,
    Seychelles = 188,
    Slachen_Glacier = 189,
    Sierra_Leone = 190,
    Singapore = 191,
    Sint_Maarten = 192,
    Slovakia = 193,
    Slovenia = 194,
    Solomon_Islands = 195,
    Somalia = 196,
    Somaliland = 197,
    South_Africa = 198,
    South_Georgia_and_Soutch_Sandwich_Islands = 199,
    South_Korea = 200,
    South_Sudan = 201,
    Spain = 202,
    Sri_Lanka = 203,
    Sudan = 204,
    Suriname = 205,
    Swaziland = 206,
    Sweden = 207,
    Switzerland = 208,
    Syria = 209,
    Taiwan = 210,
    Tajkistan = 211,
    Thailand = 212,
    The_Bahamas = 213,
    Togo = 214,
    Tonga = 215,
    Trinidad_and_Tobago = 216,
    Tunisia = 217,
    Turkey = 218,
    Turkmenistan = 219,
    Turks_and_Calcos_Islands = 220,
    Uganda = 221,
    Ukraine = 222,
    United_Arab_Emirates = 223,
    United_Kingdom = 224,
    United_Republic_of_Tanzania = 225,
    United_States_Of_America = 226,
    United_States_Virgin_Islands = 227,
    Uruguay = 228,
    Uzbekistan = 229,
    Vanuatu = 230,
    Venezuela = 231,
    Vietnam = 232,
    Walls_and_Futuna = 234,
    Western_Sahara = 235,
    Yemen = 236,
    Zambia = 237,
    Zimbabwe = 238

}


public class Flag : NetworkBehaviour
{
    private Player player;

    public SpriteRenderer flagRenderer;
    [SyncVar]
    public string selectedNation;

    public string appliedNation;
    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        if (!player) player = Player.localPlayer;
        if (!player) return;

        if (selectedNation != string.Empty)
        {
            for (int i = 0; i < GeneralManager.singleton.flagSprite.Count; i++)
            {
                if (GeneralManager.singleton.flagSprite[i].name == selectedNation)
                {
                    flagRenderer.sprite = GeneralManager.singleton.flagSprite[i];
                }
            }
            appliedNation = selectedNation;
            selectedNation = string.Empty;
        }
    }
}
